name: first_flutter_v1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.8

  # State Management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # Networking & DI
  http: ^1.5.0
  get_it: ^9.0.5

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.3

  # Models & Serialization
  equatable: ^2.0.7
  freezed_annotation: ^2.4.1 # Added for Freezed
  json_annotation: ^4.9.0    # Added for JsonSerializable

  # Utils
  intl: ^0.19.0
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.11      # Added for Code Generation
  freezed: ^2.5.2             # Added for Freezed
  json_serializable: ^6.8.0 # Added for JsonSerializable

flutter:
  uses-material-design: true
